{% set version = "0.0.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-autoshiny
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/autoshiny_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/autoshiny/autoshiny_{{ version }}.tar.gz
  sha256: 78bdcf3971df7621851eaa98febdc37c20e640f3b1e26450f7df608a00d39943

build:
  noarch: generic
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-shiny
  run:
    - r-base
    - r-shiny

test:
  commands:
    - $R -e "library('autoshiny')"           # [not win]
    - "\"%R%\" -e \"library('autoshiny')\""  # [win]

about:
  home: https://github.com/alekrutkowski/autoshiny
  license: GPL-2.0-only
  summary: Static code compilation of a 'shiny' app given an R function (into 'ui.R' and 'server.R' files or into a 'shiny' app object). See examples at <https://github.com/alekrutkowski/autoshiny>.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
