appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: sXTIaX3h5qGKh27KQeHxtoAd5t3PFd1iVWgwqc4vq6tBq//tUuI8qq/h8GQHsO2JGSkqtPVigPynxLL27rRpgHjNtlpjk73hMY9yh5hGDlbB5bJhaaR2fj2mCVWiQacfhNZ118eqUQM1Ma5wxghOSnnr4fBAb+RoYMTz1b0QZzeIICR9zQdxyNFDE3NHszruFeHPjSQhCEfVnLQ8ZEbqMPe/yYXeP5qPgUOIFpoinPjvM8eYuCBcjWmQCsPW9rAGahU7i0j+bcmf6lZN+IYqjDux+V4Y+4xfjPXbX0fxYZTkaAWy3ZGfJpx112kMzTR4xF2JP/inB5pnbduNTwxvezjTyKEkS2hsL68v5+tzZfadYHYWv2QR2gl1vaU67g1a7mB8IngExFVacunZY2ke8edNFbgff/MvqByM0cE31h39Lb346YRw8LHYvvKU3pmoGjXd2TkLk45OfWtp/vSHoOatOw83UowwbBPptcB2XEakP4JGVQBXxp0ckT41YwuCsXH0y4dG1nnPntv5QFkgBevyOL1sp7uQWD9tged5es/JaxZ7+E2prg83u4+EaPpRVZAs6RpEjePoH+4qPCTF57S6nSlSTL9Vy22wmnzF9a6Rk7Xb3+rrwHIll4gF8Wubq+aCtslN0k0uhQqns0oUtGf97XwYGAnSVA5eSC16Ytw=}
